# Generated by Django 2.2 on 2021-11-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211029_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='getqoute',
            name='is_number_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='getqoute',
            name='crockeryunit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='getqoute',
            name='customer_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='getqoute',
            name='entertainmentunit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='getqoute',
            name='kitchen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='getqoute',
            name='poojaroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='getqoute',
            name='studyunit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='getqoute',
            name='wardrobe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='getqoute',
            name='washroom',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
