# Generated by Django 2.2 on 2021-11-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211106_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getqoute',
            name='washroom',
        ),
        migrations.AddField(
            model_name='getqoute',
            name='budget',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='getqoute',
            name='ownertype',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='getqoute',
            name='possesion_type',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
