# Generated by Django 2.2 on 2021-11-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211108_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='getqoute',
            name='reg_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
